Room Class Reference
Backend class representing a room.
#include <room.h>
Signals
void connectionsUpdated ()
void nodesUpdated ()
void fileChanged ()
void roomHaveChanged ()
void roomLoaded ()
Public Member Functions
Room (QObject *parent=nullptr)
Default constructor.
QQmlListProperty< Connection > connections ()
Getter method to expose the list of connections to QML.
QQmlListProperty< Node > nodes ()
Getter method to expose the list of nodes to QML.
QUrl file () const
Getter method to expose the file used for saving to QML.
void setFile (const QUrl &url)
Setter to change the file in which changes are to be saved.
Q_INVOKABLE bool deleteNode (Node *node)
QML exposed method to remove nodes from the room.
Q_INVOKABLE bool connected (Node *a, Node *b, int direction=Node::Input)
Checks if two nodes are connected in a certain direction.
Q_INVOKABLE bool canConnect (Node *a, Node *b, int direction=Node::Input)
Checks all conditions before connecting two nodes.
Q_INVOKABLE void removeConnections (Node *a, Node *b, int t=Node::Input)
Breaks any connections between two nodes in a certain direction.
Q_INVOKABLE void createConnection (Node *a, Node *b, int t=Node::Input)
Establish a connection between two nodes in a certain direction.
Q_INVOKABLE bool hasOutConnection (Node *node)
Check if a node is the sender in any connection in the room.
Q_INVOKABLE bool hasInConnection (Node *node)
Check if a node is the receiver in any connection in the room.
Q_INVOKABLE void evaluate (Node *node)
Change the output value of a node based on connections and the nodes' configuration.
Q_INVOKABLE void initSocket ()
Initalize the udp socket to read and send osc messages.
Q_INVOKABLE void save ()
Save changes made to the room in a file.
Q_INVOKABLE void save (const QUrl &url)
Q_INVOKABLE void load (const QUrl &url)
Loaded the content of a file.
Q_INVOKABLE bool savedBefore () const
Checks if the room have been saved before.
Q_INVOKABLE bool changesSaved () const
Checks if the room has unsaved changed.
Q_INVOKABLE bool hasMoreLoaded () const
Check if there are more json objects to load.
Q_INVOKABLE void loadNextNode (Node *node)
Load the next json object, if any, into a node.
Q_INVOKABLE void loadConnections ()
Load all the connections loaded as json object into Connection objects.
Q_INVOKABLE int nextType ()
Get the type of the next node, if any, to be read into a Node object.
void read (const QJsonObject &json)
Read a json object into the room.
QJsonObject write () const
Serialize the room.
Properties
QQmlListProperty< Connection > connections
QQmlListProperty< Node > nodes
QUrl file
Private Slots
void readPendingDatagrams ()
Read pending UDP datagrams.
void sendMessage (Node *node)
Send an OSC message based on information in a node.
Private Member Functions
void removeConnections (Node *node)
Remove all connections the specified node is part of, either as sender or receiver.
bool getValue (const Node *node) const
Getter to read the output of a node.
void processBundle (OscBundle *bundle)
Read the content of a bundle and update the room.
void processMessage (OscMessage *message)
Read the content of a message and update the room.
bool looping (Node *a, Node *b, int direction)
Check if a connection between to nodes would create a loop.
bool networkLoop (Node *a, Node *b, int direction)
Check if a connection between two nodes would create a network loop.
bool chained (Node *a, Node *b)
Check if two nodes are part of the same chain of connection.
Static Private Member Functions
static void clearNodes (QQmlListProperty< Node > *list)
Clear a list of nodes.
static void clearConnections (QQmlListProperty< Connection > *list)
Clear a list of connections.
static void addNode (QQmlListProperty< Node > *list, Node *node)
Add a Node object to a list.
static void addConnection (QQmlListProperty< Connection > *list, Connection *connection)
Add a Connection object to a list.
static int countNodes (QQmlListProperty< Node > *list)
Get the length of a list of nodes.
static int countConnections (QQmlListProperty< Connection > *list)
Get the length of a list of connections.
static Node * getNode (QQmlListProperty< Node > *list, int index)
Get a node from a list.
static Connection * getConnection (QQmlListProperty< Connection > *list, int index)
Get a connection from a list.
Private Attributes
QList< Connection * > m_connections
QList< Node * > m_nodes
QJsonArray m_jsonNodes
QJsonArray m_jsonConnections
QHash< qulonglong, Node * > m_nodeHash
QUdpSocket * m_sock
QFile m_file
bool m_changeSaved = true
Detailed Description
Backend class representing a room.
This class manages the interactions with and between nodes as well as the writing and reading of files from/to memory.
Constructor & Destructor Documentation
Room()
Room::Room (QObject * parent = nullptr) [explicit]
Default constructor.
Parameters
parent Parent of the room to create.
References m_changeSaved, and roomHaveChanged().
Member Function Documentation
connections()
QQmlListProperty<Connection> Room::connections ()
Getter method to expose the list of connections to QML.
Returns
A list of all the connections created in this room.
nodes()
QQmlListProperty<Node> Room::nodes ()
Getter method to expose the list of nodes to QML.
Returns
A list of all the nodes created in this room.
file()
QUrl Room::file () const
Getter method to expose the file used for saving to QML.
Returns
The url of the current file in which changes are to be saved.
setFile()
void Room::setFile (const QUrl & url)
Setter to change the file in which changes are to be saved.
Parameters
url The url of the new file.
References fileChanged(), and m_file.
deleteNode()
bool Room::deleteNode (Node * node)
QML exposed method to remove nodes from the room.
Parameters
node The node to be deleted.
Returns
Return true if a node have been successfully deleted.
See also
Connection
Room::removeConnections
Room::connected
References connectionsUpdated(), m_nodes, nodesUpdated(), and removeConnections().
connected()
bool Room::connected (Node * a, Node * b, int direction = Node::Input)
Checks if two nodes are connected in a certain direction.
Parameters
a first node
b second node
direction of the connection
Returns
Return if the two nodes are connected in the specified direction.
See also
Room::canConnect
Node::Type
References m_connections.
canConnect()
bool Room::canConnect (Node * a, Node * b, int direction = Node::Input)
Checks all conditions before connecting two nodes.
See also
Room::connected
Parameters
a first node
b second node
direction Direction of the connection
Returns
Return true if connecting the two nodes would generate no logic issue, such as loops.
References looping().
removeConnections() [1/2]
void Room::removeConnections (Node * a, Node * b, int t = Node::Input)
Breaks any connections between two nodes in a certain direction.
See also
Room::connected
Parameters
a first node
b second node
direction Direction of the connection
See also
Room::connected
References m_connections.
createConnection()
void Room::createConnection (Node * a, Node * b, int t = Node::Input)
Establish a connection between two nodes in a certain direction.
See also
Room::connected
Parameters
a first node
b second node
direction Direction of the connection
See also
Room::connected
References m_connections, and networkLoop().
hasOutConnection()
bool Room::hasOutConnection (Node * node)
Check if a node is the sender in any connection in the room.
Parameters
node The node to check
Returns
Return true if the node is part of any connection in the room as the sender.
References m_connections.
hasInConnection()
bool Room::hasInConnection (Node * node)
Check if a node is the receiver in any connection in the room.
Parameters
node The node to check
Returns
Return true if the node is part of any connection in the room as the receiver.
References m_connections.
evaluate()
void Room::evaluate (Node * node)
Change the output value of a node based on connections and the nodes' configuration.
Parameters
node The node to evaluate
References getValue(), and m_connections.
save()
void Room::save ()
Save changes made to the room in a file.
See also
Room::m_file
Room::setFile
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
Room::save
References m_changeSaved, m_file, and write().
load()
void Room::load (const QUrl & url)
Loaded the content of a file.
See also
Room::loadNextNode
Room::loadConnections
References file(), read(), and roomLoaded().
savedBefore()
bool Room::savedBefore () const
Checks if the room have been saved before.
Returns
Return true if the room have been saved.
See also
Room::save
References m_file.
changesSaved()
bool Room::changesSaved () const
Checks if the room has unsaved changed.
Returns
Return true if the room have not been modified since the last write.
See also
Room::savedBefore
Room::save
References m_changeSaved.
hasMoreLoaded()
bool Room::hasMoreLoaded () const
Check if there are more json objects to load.
Returns
Return true if the list Room::m_jsonNodes is not empty.
References m_jsonNodes.
loadNextNode()
void Room::loadNextNode (Node * node)
Load the next json object, if any, into a node.
Parameters
node The node in which the next json object should be read.
See also
Room::hasMoreLoaded
References m_jsonNodes, m_nodeHash, m_nodes, roomHaveChanged(), and sendMessage().
loadConnections()
void Room::loadConnections ()
Load all the connections loaded as json object into Connection objects.
See also
Room::load
Room::loadNextNode
References m_connections, m_jsonConnections, and m_nodeHash.
nextType()
int Room::nextType ()
Get the type of the next node, if any, to be read into a Node object.
Returns
Return the type of the next json object to be read.
See also
Node::Type
Node::hasMoreLoaded
References m_jsonNodes.
read()
void Room::read (const QJsonObject & json)
Read a json object into the room.
Parameters
json JSON object to be read.
References m_connections, m_jsonConnections, m_jsonNodes, m_nodeHash, and m_nodes.
write()
QJsonObject Room::write () const
Serialize the room.
Returns
Return the JSON object containing the data.
References m_connections, and m_nodes.
connectionsUpdated
void Room::connectionsUpdated () [signal]
Notify a change in the list of connections.
nodesUpdated
void Room::nodesUpdated () [signal]
Notify a change in the list of connections.
fileChanged
void Room::fileChanged () [signal]
Notify when the default file has changed.
roomHaveChanged
void Room::roomHaveChanged () [signal]
Notify when the room have changed. Used to relay change in individual nodes to the room.
roomLoaded
void Room::roomLoaded () [signal]
Notify when the reading of a file have completed.
removeConnections() [2/2]
void Room::removeConnections (Node * node) [private]
Remove all connections the specified node is part of, either as sender or receiver.
Useful to clean up before deleting a node.
Parameters
node The node to clean.
References connectionsUpdated(), and m_connections.
getValue()
bool Room::getValue (const Node * node) const [private]
Getter to read the output of a node.
Parameters
node The node to be evaluated.
Returns
Returns the output value of the node.
See also
Room::evaluate
References hasInConnection(), and m_connections.
processBundle()
void Room::processBundle (OscBundle * bundle) [private]
Read the content of a bundle and update the room.
Parameters
bundle The bundle to read.
References processMessage().
processMessage()
void Room::processMessage (OscMessage * message) [private]
Read the content of a message and update the room.
Parameters
message The message to read.
References m_nodes.
looping()
bool Room::looping (Node * a, Node * b, int direction) [private]
Check if a connection between to nodes would create a loop.
Parameters
a The first node.
b The second node.
direction The direction of the connection.
Returns
Return true if the connection would create a loop.
See also
Romm::canConnect
References connected(), and m_connections.
networkLoop()
bool Room::networkLoop (Node * a, Node * b, int direction) [private]
Check if a connection between two nodes would create a network loop.
Parameters
a The first node.
b The second node.
direction The direction of the connection.
Returns
Return true if the connection would generate a network loop.
References chained(), and m_connections.
chained()
bool Room::chained (Node * a, Node * b) [private]
Check if two nodes are part of the same chain of connection.
Parameters
a The first node.
b The second node.
Returns
Return true if the two ndoes are connected.
References connected(), and m_connections.
clearNodes()
void Room::clearNodes (QQmlListProperty< Node > * list) [static], [private]
Clear a list of nodes.
Parameters
list The list to be cleared.
clearConnections()
void Room::clearConnections (QQmlListProperty< Connection > * list) [static], [private]
Clear a list of connections.
Parameters
list The list to be cleared.
addNode()
void Room::addNode (QQmlListProperty< Node > * list, Node * node) [static], [private]
Add a Node object to a list.
Parameters
list The list to add the node to.
node The node to add to the list.
References roomHaveChanged(), and sendMessage().
addConnection()
void Room::addConnection (QQmlListProperty< Connection > * list, Connection * connection) [static], [private]
Add a Connection object to a list.
Parameters
list The list to add the connection to.
connection The connection to add to the list.
countNodes()
int Room::countNodes (QQmlListProperty< Node > * list) [static], [private]
Get the length of a list of nodes.
Parameters
list The list to get the length of.
Returns
Return the length of the list.
countConnections()
int Room::countConnections (QQmlListProperty< Connection > * list) [static], [private]
Get the length of a list of connections.
Parameters
list The list to get the length of.
Returns
Return the length of the list.
getNode()
Node * Room::getNode (QQmlListProperty< Node > * list, int index) [static], [private]
Get a node from a list.
Parameters
list The list from which to get the node.
index The index of the node to get.
Returns
Return the node at the specified position in the list.
getConnection()
Connection * Room::getConnection (QQmlListProperty< Connection > * list, int index) [static], [private]
Get a connection from a list.
Parameters
list The list from which to get the connection.
index The index of the connection to get.
Returns
Return the connection at the specified position in the list.
sendMessage
void Room::sendMessage (Node * node) [private], [slot]
Send an OSC message based on information in a node.
Parameters
node The node from which the content of the message is retrieved.
References m_sock.
Member Data Documentation
m_connections
QList<Connection*> Room::m_connections [private]
List of connections created in the room.
m_nodes
QList<Node*> Room::m_nodes [private]
List of nodes created in the room.
m_jsonNodes
QJsonArray Room::m_jsonNodes [private]
List of nodes loaded but not yet created.
m_jsonConnections
QJsonArray Room::m_jsonConnections [private]
List of connections loaded but not yet created.
m_nodeHash
QHash<qulonglong, Node*> Room::m_nodeHash [private]
Hashmap used to rebuild the connections from loaded items. -- (pointer swizzling)
m_sock
QUdpSocket* Room::m_sock [private]
Socket to listen for OSC messages.
m_file
QFile Room::m_file [private]
File in which changes are to be saved.
See also
Room::save
m_changeSaved
bool Room::m_changeSaved = true [private]
Boolean holding wether there are unsaved changes in the room currently
Property Documentation
connections
QQmlListProperty< Connection > Room::connections [read]
See also
Room::connections
nodes
QQmlListProperty< Node > Room::nodes [read]
See also
Room::nodes
file
QUrl Room::file [read], [write]
See also
Room::file
The documentation for this class was generated from the following files:
include/room.h
src/cpp/room.cpp